int bit_mask(int low, int high);
char * getBytes(  int source,   char *bytes);
int joinBytes(  char *bytes);
int getBits(int low, int high, int source);
int setBits(int low, int high, int source);
int clearBits(int low, int high, int source);
int assignBit(int bitNumber, int bitValue, int source);
char getByteNumber(int byteNo, int source);
int setByteNumber(int byteNo, char byteValue, int source);
int buildWord(char byte0, char byte1, char byte2, char byte3);
bool isNeg(int source);
void expandBits(  int source, char bits[36]);
void clearBuffer(char * buff, int size);
char * revchararr( char * arr,   short int size);
void remchars(char *str, char c);
bool valinarr(int val, int * arr, int size);
void chopStart(char *str, size_t n);
size_t splitString(char *line, char ***sve_record, char *split);
